alias: Minimote button 1 short press
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_4
      scene_id: 1
action:
  - service: light.turn_on
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3_0
      brightness: 255

