alias: Turn hallway lights off motion
trigger:
  - platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
    from: '8'
    to: '0'
action:
  - service: light.turn_on
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3_0
      brightness: 0

